codec:
  model_path: /DKUdata/tangbl/FunCodec/egs/LibriTTS/codec/exp/audio_codec-encodec-zh_en-general-16k-nq32ds640-pytorch/model.pth
  config_path: /DKUdata/tangbl/FunCodec/egs/LibriTTS/codec/exp/audio_codec-encodec-zh_en-general-16k-nq32ds640-pytorch/config.yaml
  bypass_quantizer: True

model:
  type: TransformerCrossTarget
  mamba_num: 6
  d_model: 128
  d_state: 128
  d_conv: 4
  expand: 2
  sampling_rate: 16000
  
data:
  name: LibriMix # have to be in [WHAM, or LibriMix ]
  type: target # [noise, target]
  length: 64000 # 4 second x 16000 sample rate
  tr: 
    mix: /Netdata/2021/zb/data/LibriMix/Libri2Mix/wav16k/min/lists/train/all/mix.scp
    source: /Netdata/2021/zb/data/LibriMix/Libri2Mix/wav16k/min/lists/train/all/s1.scp
  cv:
    mix: /Netdata/2021/zb/data/LibriMix/Libri2Mix/wav16k/min/lists/test/mix.scp
    source: /Netdata/2021/zb/data/LibriMix/Libri2Mix/wav16k/min/lists/test/s1.scp
  tt:
    mix: /Netdata/2021/zb/data/LibriMix/Libri2Mix/wav16k/min/lists/dev/mix.scp
    source: /Netdata/2021/zb/data/LibriMix/Libri2Mix/wav16k/min/lists/dev/s1.scp

batch_size: 6
epoch: 100
log_interval: 10 ## every 10 batches

optim:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0

loss: CrossEntropyTarget # [Sisnr, Mse, Cos]