codec:
  model_path: /DKUdata/tangbl/FunCodec/egs/LibriTTS/codec/exp/audio_codec-encodec-zh_en-general-16k-nq32ds640-pytorch/model.pth
  config_path: /DKUdata/tangbl/FunCodec/egs/LibriTTS/codec/exp/audio_codec-encodec-zh_en-general-16k-nq32ds640-pytorch/config.yaml
  bypass_quantizer: True

model:
  type: SelmCodec
  mamba_num: 6
  d_model: 128
  d_state: 128
  d_conv: 4
  expand: 2
  sampling_rate: 16000
  
data:
  name: LibriMix # have to be in [WHAM, or LibriMix ]
  type: noise # [noise, target]
  emb: true
  length: 500 # [B, 1024, 500] # if emb is true, this stands for the length of the embedding 
  tr: 
    mix: /DKUdata/tangbl/dac_codec/data/libri2mix/emb/list/train/mix.scp
    source: /DKUdata/tangbl/dac_codec/data/libri2mix/emb/list/train/s1.scp
  cv:
    mix: /DKUdata/tangbl/dac_codec/data/libri2mix/emb/list/test/mix.scp
    source: /DKUdata/tangbl/dac_codec/data/libri2mix/emb/list/test/s1.scp
  tt:
    mix: /DKUdata/tangbl/dac_codec/data/libri2mix/emb/list/dev/mix.scp
    source: /DKUdata/tangbl/dac_codec/data/libri2mix/emb/list/dev/s1.scp

batch_size: 5
epoch: 100
log_interval: 10 ## every 10 batches

optim:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0

loss: selm # [Sisnr, Mse, Cos]