codec: ## this field does not matter
  model_path: /DKUdata/tangbl/FunCodec/egs/LibriTTS/codec/exp/audio_codec-encodec-en-libritts-16k-nq32ds640-pytorch/model.pth
  config_path: /DKUdata/tangbl/FunCodec/egs/LibriTTS/codec/exp/audio_codec-encodec-en-libritts-16k-nq32ds640-pytorch/config.yaml
model:
  type: MambaCodec
  mamba_num: 6
  d_model: 128
  d_state: 128
  d_conv: 4
  expand: 2
  sampling_rate: 16000
  bypass_quantizer: False
  
  
data:
  name: LibriMix # have to be in [WHAM, or LibriMix ]
  type: noise # [noise, target]
  length: 160000 # 6 second x 16000 sample rate
  tr: 
    mix: /Netdata/2021/zb/data/LibriMix/Libri2Mix/Libri2Mix/wav16k/min/list/train/mix.scp
    source: /Netdata/2021/zb/data/LibriMix/Libri2Mix/Libri2Mix/wav16k/min/list/train/s1.scp
  cv:
    mix: /Netdata/2021/zb/data/LibriMix/Libri2Mix/Libri2Mix/wav16k/min/list/test/mix.scp
    source: /Netdata/2021/zb/data/LibriMix/Libri2Mix/Libri2Mix/wav16k/min/list/test/s1.scp
  tt:
    mix: /Netdata/2021/zb/data/LibriMix/Libri2Mix/Libri2Mix/wav16k/min/list/dev/mix.scp
    source: /Netdata/2021/zb/data/LibriMix/Libri2Mix/Libri2Mix/wav16k/min/list/dev/s1.scp
batch_size: 16
epoch: 100
log_interval: 10 ## every 10 * 16 batches on every process

optim:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0

loss: mse # [Sisnr, Mse, Cos]